name: name_me
description: "A new Flutter project."
publish_to: "none"
version: 0.1.3+4

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  change_app_package_name: ^1.4.0
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  firebase_core: ^3.8.1
  firebase_vertexai: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  lottie: ^3.1.3
  rename_app: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/lottie/
    - assets/images/
